### ISSUE TITLE
There's Nothing There

### ISSUE THREAD

**Issue by hs115488** [Emuneshar/Summer-2020#1]
There's no README

**Comment by Emuneshar** [comment]
Was I supposed to make one? I'm still figuring this all out.

**Comment by hs115488** [comment]
You're supposed at least add one file to these repositories. When creating a repository, there is usually an option to add an README. That is sort of like documentation of your code stored in your repository, It also keeps your repository open so others can contribute to it. If the repo is empty, no can fork it.
